# Generated by Django 4.2.4 on 2023-09-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=20)),
                ('upper_tunnel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottom_tunnel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checking_frequency', models.PositiveIntegerField()),
            ],
        ),
    ]
